[examples] add rep_qat script, CLE util and bn_rebuid util
alibaba/TinyNeuralNetwork pull request #131
Opened 2022-11-07 07:22 UTC by zk1998

2022-11-07 08:30 UTC, peterjc123 requested changes

2022-11-07 08:30 UTC, peterjc123 commented on examples/quantization/rep_qat.py
> +    """The help function to get conv_bn folded model for mobilenetv1."""
help -> helper

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/bn_rebuild.py
> +        if isinstance(mod, nn.Conv2d) and name in layer_fused_bn:
You will need to do recursion in the `else` branch. Otherwise, the modules in a `nn.Sequential` object won't be updated.

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/bn_rebuild.py
> +    for name, mod in model.named_children():
See above.

2022-11-07 08:30 UTC, peterjc123 commented on examples/quantization/rep_qat.py
> +            if type(quantizer) != PostQuantizer and LooseVersion(torch.__version__) >= LooseVersion('1.11.0'):
Please remove line 159-161.

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/bn_rebuild.py
> +class ConvBnForward(nn.Module):
If this is limited to Conv2d, then it should be named as `ConvBn2dForward`. But I guess it is simpler to just implement the support for Conv1d.

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/cross_layer_equal.py
> +"""Cross Layer Equalization
It sounds weird that the file ends with `equal`. `equalize` is better.

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/cross_layer_equal.py
> +def weight_euqal_(model: nn.Module, dummy_input, threshold=1000):
euqal -> equal

2022-11-07 08:30 UTC, peterjc123 commented on tinynn/util/cross_layer_equal.py
> +            S1[-1] = s - s + 1
Seems weird. Please double check.

2022-11-07 08:30 UTC, zk1998 commented
您好，我已经收到您的邮件，我会尽快查看并在第一时间回复您。

2022-11-07 08:50 UTC, dinghuanghao commented on examples/quantization/rep_qat.py
> +from tinynn.util.cross_layer_equal import weight_euqal_
It is more reasonable to move `cross_layer_equal` to `tinynn/graph/quantization directory`

2022-11-07 08:50 UTC, dinghuanghao commented on examples/quantization/rep_qat.py
> +        weight_euqal_(fused_model, dummy_input, threshold=1000)
The internal interface should not be exposed to the outside, you can encapsulate a more understandable interface, such as `cross_layer_equal`

2022-11-07 08:50 UTC, dinghuanghao commented on examples/quantization/rep_qat.py
> +    fused_model = model_add_bn(fused_model, layers_fused_bn, torch.device('cuda'), calibrate, context)
The logic of 52, 54 and 56 can be merged into `model_add_bn`

2022-11-08 07:17 UTC, peterjc123 reviewed
Suggestions:
(a) Consider adding a `README` document describing the main problem and the whole process of quantization for RepVGG-like models.

From a user's perspective, it seems quite confusing with the code, even there are some inline comments. They may know what `RepVGG` is, but not `get_fused_model` and `cross_layer_equalize`. Thus make them unwilling to try out your work.

(b) Add code example for PTQ for RepVGG-like models

2022-11-08 07:17 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +        if hasattr(model, layer_name) and isinstance(getattr(model, layer_name), torch.nn.Conv2d):
Consider using the logic in `QATQuantizer.get_submodule_with_parent_from_name`.

2022-11-10 07:36 UTC, merged