[examples] Add high_bias_absorb in CLE
alibaba/TinyNeuralNetwork pull request #155
Opened 2022-12-13 09:53 UTC by zk1998

2022-12-14 09:54 UTC, peterjc123 requested changes
需要优化一下

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/README_zh-CN.md
> +5. 在使用CLE的实际过程中，发现部分卷积的卷积核对应的特征输出会被放大10e8倍导致激活值量化失败，可以通过控制参数`threshold`来避免激活值量化失效。此外，单独进行一次CLE时，权重的均匀化程度有时还不能保证，可以尝试多次进行CLE进一步提升量化精度。
在使用的CLE的过程中，发现由于对weight的量化参数的调整，导致卷积部分通道的激活值被放大xxx，从而无法正常量化，在这种情况下，可以使用xxx

此外，若只进行一次CLE，权重的量化参数仍可能不均匀，导致较大的量化误差，可以尝试多次进行CLE进一步提升量化精度。

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/README_zh-CN.md
> +6. 可选操作：在量化时训练准备阶段，对rep类模型进行CLE变换和BN重建之后，可以对浮点模型进行finetune训练，使模型量化训练更加稳定。
在开始QAT之前，对RepVGG-like的模型。。。。

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/rep_ptq.py
> +    # Provide your pretrain model
pretrained

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/rep_ptq.py
> +    # Define the train_related context
training-related

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/rep_ptq.py
> +    # if your pretrained model is Rep_style_deploy, use the following line to do bn restore to do High Bias Absorb.
首字母大写
Rep_style_deploy是啥？RepVGG-like
to do xxx to do yyy -> to do xxx and yyy

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/rep_ptq.py
> +    # Do CLE, if weight has some outliers which is hard to quantize, considering trying CLE.
别再用DO了啊，Apply 或者 Perform也能用啊

2022-12-14 09:54 UTC, peterjc123 commented on examples/quantization/rep_quantization/rep_ptq.py
> +    # Now you get a model whose weights and activations is easy to quantize, continue to do ptq.
is -> are
Now -> Now that
do的问题

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +            setattr(getattr(graph.module, quant_nodes[0]), 'fused_bn', bn_cur)
最好别直接打在module上面，就算一定要打也不要用这个名字，可以前面加个下划线之类的，避免冲突

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +        bias_correct = reduced_weight * c
注意no_grad，或者用.detach()

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +    with model_tracer() and torch.no_grad():
虽然可以省掉一行，但是这取决于前面这个条件要返回true，考虑用with (A,B): 这样返回啥都行了

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +    with torch.no_grad() and model_tracer():
一样

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +                log.info(f'{k}: {param[k].data.item():.5f} -> {after_max.data.item():.5f}')
只有after_max有效才打吧，否则打出很多无关的东西

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +                log.info(f'{k}: {param[k].data.item():.5f} -> {after_max.data.item():.5f}')
而且最好是endswith('.weight')这样，否则当中有个叫weight的什么东西直接不对了

2022-12-14 09:54 UTC, peterjc123 commented on tinynn/graph/quantization/cross_layer_equalization.py
> +            if 'weight' in k:
一样

2022-12-14 09:54 UTC, zk1998 commented
您好，我已经收到您的邮件，我会尽快查看并在第一时间回复您。

2022-12-15 10:08 UTC, peterjc123 requested changes

2023-01-03 02:57 UTC, peterjc123 approved these changes

2023-01-03 02:57 UTC, merged

2023-01-03 02:57 UTC, zk1998 commented
您好，我已经收到您的邮件，我会尽快查看并在第一时间回复您。