[quantizer] add fc-1d rewrite
alibaba/TinyNeuralNetwork pull request #99
Opened 2022-07-20 10:27 UTC by zk1998

2022-07-21 02:36 UTC, peterjc123 requested changes

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +# Processed Rewrite to fuse rules
Why was capitalized character used here?

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +        print(f'found nodes to fuse: {quant_list}')
Please don't use `print` here.

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +                        log.info('the fc-bn\'s input dimension != 2')
Consider using the`DEBUG` level here. It's a confusing message for the users.

2022-07-21 02:36 UTC, peterjc123 commented on tests/quantizer_test.py
> +    def test_fc_bn_fuse(self):
Please test Linear with `bias=False` as well.

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +        for idx, names in enumerate(reversed(rewrite_fuse_names_list)):  # names should be ['fc', 'bn']
Please remove the comment in this line.

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +            if len(names) == 2:
If you add this check, please remember to handle the `else` codepath.

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +                if type(mod_fc) == nn.Linear and type(mod_bn) == nn.BatchNorm1d:
If you add this check, please remember to handle the `else` codepath.

2022-07-21 02:36 UTC, peterjc123 commented on tinynn/graph/quantization/quantizer.py
> +def load_processed_rewrite_to_fuse_rules():
Consider refactoring the functions. As can be seen that Line 2071-2079, 2087- 2097 and 2104-2114 are almost the same.

2022-07-21 04:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/TinyNeuralNetwork?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/TinyNeuralNetwork?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/TinyNeuralNetwork?pullRequest=99) it.</sub>

2022-07-21 04:07 UTC, zk1998 commented
您好，我已经收到您的邮件，我会尽快查看并在第一时间回复您。

2022-07-22 03:24 UTC, peterjc123 approved these changes

2022-07-22 03:55 UTC, merged

2022-10-11 09:23 UTC, zk1998 commented
您好，我已经收到您的邮件，我会尽快查看并在第一时间回复您。